export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const ROBOTS_PENDING = "ROBOTS_PENDING";
export const ROBOTS_SUCCESSFUL = "ROBOTS_SUCCESSFUL";
export const ROBOTS_FAILED = "ROBOTS_FAILED";
